#- name: set NODE_IP var
#  set_fact:
#    NODE_IP="{{ ansible_default_ipv4.address }}"

- name: cp kube-apiserver-csr.json to /opt/kubernetes/ssl
  template:
    src: kube-apiserver/kube-apiserver-csr.json.j2
    dest: /opt/kubernetes/ssl/kube-apiserver-csr.json
    owner: root
    group: root
    mode: 0644

- name: generate kube-apiserver.pem and kube-apiserver-key.pem
  shell: /opt/kubernetes/bin/cfssl gencert -ca=/opt/kubernetes/ssl/ca.pem -ca-key=/opt/kubernetes/ssl/ca-key.pem -config=/opt/kubernetes/ssl/ca-config.json -profile=kubernetes kube-apiserver-csr.json | /opt/kubernetes/bin/cfssljson -bare kube-apiserver
  args:
    chdir: /opt/kubernetes/ssl
    creates: /opt/kubernetes/ssl/kube-apiserver.pem

- name: cp proxy-client-csr.json to /opt/kubernetes/ssl
  template:
    src: kube-apiserver/proxy-client-csr.json.j2
    dest: /opt/kubernetes/ssl/proxy-client-csr.json
    owner: root
    group: root
    mode: 0644

- name: generate proxy-client.pem and proxy-client-key.pem
  shell: /opt/kubernetes/bin/cfssl gencert -ca=/opt/kubernetes/ssl/ca.pem -ca-key=/opt/kubernetes/ssl/ca-key.pem -config=/opt/kubernetes/ssl/ca-config.json -profile=kubernetes proxy-client-csr.json | /opt/kubernetes/bin/cfssljson -bare proxy-client
  args:
    chdir: /opt/kubernetes/ssl
    creates: /opt/kubernetes/ssl/proxy-client.pem

- name: cp bootstrap-token.csv to /opt/kubernetes/ssl
  template:
    src: kube-apiserver/bootstrap-token.csv.j2 
    dest: /opt/kubernetes/cfg/bootstrap-token.csv
    owner: root
    group: root
    mode: 0644

- name: cp kube-apiserver bin to /opt/kubernetes/bin
  copy:
    src: k8s-master/kube-apiserver
    dest: /opt/kubernetes/bin/kube-apiserver
    owner: root
    group: root
    mode: 0755

- name: cp kube-apiserver.conf to /opt/kubernetes/cfg
  template:
    src: kube-apiserver/kube-apiserver.conf.j2
    dest: /opt/kubernetes/cfg/kube-apiserver.conf
    owner: root
    group: root
    mode: 0644
  notify: restart kube-apiserver

- name: cp kube-apiserver.service to /lib/systemd/system
  template:
    src: kube-apiserver/kube-apiserver.service.j2
    dest: /lib/systemd/system/kube-apiserver.service
    owner: root
    group: root
    mode: 0644
  notify: restart kube-apiserver

- name: start kube-apiserver
  service: 
    name: kube-apiserver
    state: started
    enabled: yes
    daemon_reload: yes
