---
# tasks file for /etc/ansible/roles/etcd
- name: cp etcd-csr.json to /opt/kubernetes/ssl
  template:
    src: etcd-csr.json.j2
    dest: /opt/kubernetes/ssl/etcd-csr.json
    owner: root
    group: root
    mode: 0644

- name: generate etcd.pem and etcd-key.pem
  shell: /opt/kubernetes/bin/cfssl gencert -ca=/opt/kubernetes/ssl/ca.pem -ca-key=/opt/kubernetes/ssl/ca-key.pem -config=/opt/kubernetes/ssl/ca-config.json -profile=kubernetes etcd-csr.json | /opt/kubernetes/bin/cfssljson -bare etcd
  args:
    chdir: /opt/kubernetes/ssl
    creates: /opt/kubernetes/ssl/etcd.pem

- name: cp etcd binary to /usr/bin
  copy: 
    src: etcd
    dest: /usr/bin/etcd
    owner: root
    group: root
    mode: 0755

- name: cp etcdctl binary to /usr/bin
  copy: 
    src: etcdctl
    dest: /usr/bin/etcdctl
    owner: root
    group: root
    mode: 0755

- name: ensure /etc/etcd directory
  file:
    path: /etc/etcd
    state: directory
    owner: root
    group: root
    mode: 0755

#- name: set NODE_IP var
#  set_fact:
#    NODE_IP="{{ ansible_default_ipv4.address }}"

- name: ensure etcd data directory
  file:
    path: /var/lib/etcd
    state: directory
    owner: root
    group: root
    mode: 0755

- name: cp etcd config to /etc/etcd
  template: 
    src: etcd.conf.j2
    dest: /etc/etcd/etcd.conf
    owner: root
    group: root
    mode: 0644

- name: cp etcd service to /lib/systemd/system
  template:
    src: etcd.service.j2
    dest: /lib/systemd/system/etcd.service
    owner: root
    group: root
    mode: 0755
  notify:
    - restart etcd

#- name: daemon reload
#  command: systemctl daemon-reload

- name: start etcd
  service:
    name: etcd
    state: started
    enabled: yes
    daemon_reload: yes
