---
# handlers file for /etc/ansible/roles/k8s-node
- name: restart kubelet
  service:
    name: kubelet
    state: restarted
    daemon_reload: yes

- name: restart kube-proxy
  service:
    name: kube-proxy
    state: restarted
    daemon_reload: yes
