- name: ensure kubelet workdir
  file: 
    path: /var/lib/kubelet
    state: directory

- name: test clusterrolebinding
  shell: /opt/kubernetes/bin/kubectl get clusterrolebinding | grep kubelet-bootstrap
  register: result
  ignore_errors: True

- name: cluster role binding
  shell: /opt/kubernetes/bin/kubectl create clusterrolebinding kubelet-bootstrap --clusterrole=system:node-bootstrapper --user=kubelet-bootstrap
  when: result.rc != 0

- name: kubeconfig-set-cluster
  command: /opt/kubernetes/bin/kubectl config set-cluster kubernetes --certificate-authority=/opt/kubernetes/ssl/ca.pem --embed-certs=true --server=https://{{ MASTER_IP }}:6443 --kubeconfig=kubelet-bootstrap.kubeconfig
  args:
    chdir: /opt/kubernetes/cfg

- name: kubeconfig-set-credentials
  command: /opt/kubernetes/bin/kubectl config set-credentials kubelet-bootstrap --token={{ BOOTSTRAP_TOKEN }} --kubeconfig=kubelet-bootstrap.kubeconfig
  args:
    chdir: /opt/kubernetes/cfg

- name: kubeconfig-set-context
  command: /opt/kubernetes/bin/kubectl config set-context default --cluster=kubernetes --user=kubelet-bootstrap --kubeconfig=kubelet-bootstrap.kubeconfig
  args:
    chdir: /opt/kubernetes/cfg

- name: kubeconfig-use-context
  command: /opt/kubernetes/bin/kubectl config use-context default --kubeconfig=kubelet-bootstrap.kubeconfig
  args:
    chdir: /opt/kubernetes/cfg

- name: cp kubelet bin file to /opt/kubernetes/bin
  copy: 
    src: k8s-node/kubelet
    dest: /opt/kubernetes/bin
    owner: root
    group: root
    mode: 0755

- name: cp kubelet.json to /opt/kubernetes/cfg
  template:
    src: kubelet/kubelet.json.j2
    dest: /opt/kubernetes/cfg/kubelet.yaml
    #dest: /opt/kubernetes/cfg/kubelet.json
    owner: root
    group: root
    mode: 0644
  notify: restart kubelet

- name: cp kubelet.service to /lib/systemd/system
  template:
    src: kubelet/kubelet.service.j2
    dest: /lib/systemd/system/kubelet.service
    owner: root
    group: root
    mode: 0644
  notify: restart kubelet

- name: start kubelet
  service:
    name: kubelet
    state: started
    enabled: yes
    daemon_reload: yes
