---
# tasks file for /etc/ansible/roles/k8s-node
- include: kubelet.yml
- include: kube-proxy.yml

- name: test approve
  shell: /opt/kubernetes/bin/kubectl get csr | grep 'Pending'
  register: result
  ignore_errors: True

- name: kubectl certificate approve
  shell: /opt/kubernetes/bin/kubectl get csr | grep 'Pending' | awk '{print $1}'| xargs /opt/kubernetes/bin/kubectl certificate approve
  when: result.rc == 0 
