---
# handlers file for /etc/ansible/roles/k8s-common
- name: restart zebra of quagga
  service: name=zebra state=restarted daemon_reload=yes

- name: restart ospfd of quagga
  service: name=ospfd state=restarted daemon_reload=yes
