---
# tasks file for /etc/ansible/roles/docker
- name: install dependent packages for ubuntu
  package: name={{ item }} state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl 
    - gnupg
    - lsb-release
  when: ansible_distribution == "Ubuntu"

- name: install dependent packages for centos
  package: name={{ item }} state=present
  with_items:
    - yum-utils
  when: ansible_distribution == "CentOS"

- name: import docker-ce repo for ubuntu
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" 
  when: ansible_distribution == "Ubuntu"

- name: import docker-ce repo for centos
  shell: yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
  when: ansible_distribution == "CentOS"

- name: install docker-ce
  package: name=docker-ce state=present
  #package: name=docker-ce=<VERSION_STRING> state=present

- name: ensure /etc/docker directory
  file: path=/etc/docker state=directory

- name: cp daemon.json to dest
  template: src=daemon.json.j2 dest=/etc/docker/daemon.json owner=root group=root mode=0644

#- name: cp docker.service to dest
#  template: src=docker.service.j2 dest=/lib/systemd/system/docker.service owner=root group=root mode=0755
#  notify: restart docker

- name: daemon-reload
  command: systemctl daemon-reload

- name: start docker
  service: name=docker.service state=started enabled=yes daemon_reload=yes
