- name: install Development Tools
  package: name={{ item }} state=present
  with_items:
    - bc
    - net-tools
    - ntpdate
    - screen 
    - unzip 
    - vim-common 
    - vim-enhanced 
    - wget 
    - zip 
    - mtr 
    - nload 
    - lrzsz 
    - iotop 
    - tree 
    - telnet 
    - iftop
    - traceroute
    - bind-utils
    - man
    - tcpdump
    - iptraf
    - atop
    - htop
    - iftop
    - wget 
    - ipvsadm
    - ipset
    - sysstat
    - conntrack
    - libseccomp
    #- '@"Development Tools"'
    #- "@Base" 
  when: ansible_distribution == "CentOS"

- name: install Development Tools
  package: name={{ item }} state=present
  with_items:
    - python-pip
    - socat
    - libcurl4-nss-dev
    - nfs-common
    - python-dev
    - python-setuptools
    - iotop
    - build-essential
    - libssl-dev
    - vim
    - make
    - gdb
    - libgcc1
    - telnet
    - zlib1g-dev
    - rpcbind
    - lrzsz
    - mtr-tiny
    - dmidecode 
    - zip
    - unzip
    - wget
    - screen
    - autoconf
    - automake
    - bc
    - bzip2
    - bison
    - cmake
    - libfreetype6-dev
    - fuse
    - libfuse-dev
    - libgeoip-dev
    - libglib2.0-0
    - libglib2.0-dev
    - libncurses5
    - libncurses5-dev
    - libpcre3
    - libpcre3-dev
    - libreadline-dev
    - git
    - net-tools                                    
    - ntpdate
    - iftop
    - atop
    - htop
  when: ansible_distribution == "Ubuntu"
