- name: install zabbix epel repo for CentOS 7
  get_url: url=https://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm dest=/tmp
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: install zabbix epel repo for Ubuntu 18.04
  get_url: url=https://repo.zabbix.com/zabbix/3.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.4-1+bionic_all.deb dest=/tmp
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18"

- name: install zabbix-agent repo for CentOS 7
  shell: rpm -i /tmp/zabbix-release-3.4-2.el7.noarch.rpm
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: install zabbix-agent repo for Ubuntu 18.04
  shell: dpkg -i /tmp/zabbix-release_3.4-1+bionic_all.deb 
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18"

- name: install zabbix-agent
  package: name=zabbix-agent state=present

- name: copy zabbix_agentd.conf to server
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Server=127.0.0.1'
    line: "Server={{ zabbix_server_ip }}"
  notify: restart zabbix-agent

- name: start zabbix-agent
  service: name=zabbix-agent state=started enabled=yes

- name: install zabbix-api
  pip: name=zabbix-api
  
- name: add zabbix hosts
  local_action:
    module: zabbix_host
    server_url: http://192.168.11.211:81/zabbix/
    login_user: admin
    login_password: 9voU2d5DJGzhgABNMbvj
    host_name: '{{inventory_hostname}}'
    visible_name: '{{ansible_fqdn.split("-")[0]}}-{{ansible_fqdn.split("-")[1]}}-{{ansible_fqdn.split("-")[2]}}_{{inventory_hostname}}'
    host_groups:
      - pk-platform
    link_templates:
      - Template OS Linux
    status: enabled
    state: present
    interfaces:
    - type: 1
      main: 1
      useip: 1
      ip: '{{inventory_hostname}}'
      dns: ""
      port: 10050
  tags:
  - set_hosts
