---
- name: set /etc/resolv.conf for CentOS 7
  template: 
    src: centos7_resolv.conf.j2 
    dest: /etc/resolv.conf 
    owner: root 
    group: root 
    mode: 0644
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: set /etc/resolv.conf for Ubuntu 18.04
  template: 
    src: ubuntu18_resolv.conf.j2 
    dest: /etc/resolv.conf 
    owner: root 
    group: root 
    mode: 0644
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18" 

- name: config dns for Ubuntu 18.04
  lineinfile:
    dest: /etc/systemd/resolved.conf
    regexp: '^#DNS='
    line: "DNS={{ dns1 }} {{ dns2 }}"
  notify: restart systemd-resolved
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18" 
