---
- name: adjust history
  lineinfile:
    dest: /etc/profile
    line: 'export HISTTIMEFORMAT="%F %T `whoami` "'

- name: change file descriptors in /etc/profile
  lineinfile:
    dest: /etc/profile
    line: 'ulimit -SHn 65535'

- name: change coredump file size in /etc/profile
  lineinfile:
    dest: /etc/profile
    line: 'ulimit -c unlimited'

- name: change limits.conf for Ubuntu 18.04
  template: 
    src: ubuntu18_limits.conf.j2
    dest: /etc/security/limits.conf 
    owner: root 
    group: root 
    mode: 0644
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18"

- name: change 20-nproc.conf for CentOS 7
  template: 
    src: centos7_20-nproc.conf.j2
    dest: /etc/security/limits.d/20-nproc.conf 
    owner: root 
    group: root 
    mode: 0644
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"