---
- name: swapoff -a
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '(.*)swap(.*)'
    replace: '#\1swap\2'

- name: check /etc/sysctl.conf exist
  stat:
    path: /etc/sysctl.conf
  register: file_exist

- name: set vm.swappiness is zero
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^vm.swappiness'
    line: 'vm.swappiness = 0'
  when: file_exist.stat.exists == true

- name: sysctl -p
  command: "sysctl -p"
